### ISSUE TITLE
Add node.body check before attempting to vist children

### ISSUE THREAD

**Issue by JamesHenry** [estools/escope#111]
Hi there,

On a couple of occasions whilst we have been developing the typescript-eslint-parser, we have come up against the fact that escope referencer throws if there is no body on a `FunctionExpression`.

In TypeScript, there are a actually a few situations where a function can be defined with no body:

```ts
function foo(bar: number): number;
```

Please see this issue for one such example: https://github.com/eslint/typescript-eslint-parser/issues/92

In some of these cases, we have worked around it by namespacing our converted ESTree-node, but it would be great if we could add a simple guard to escope to check for the existence of a body before attempting to visit its children.

I have gone ahead submitted a PR for that change here: https://github.com/estools/escope/pull/110

One idea I had was to add the typescript-eslint-parser as another third-party parser in this project, so we could add an explicit test for this case. Just let me know if that is something you would be interested in having added to the PR.

**Comment by nzakas** [comment]
@michaelficarra I think you're the only other person besides me who monitors the repo actively. Do you have thoughts about this?

**Comment by michaelficarra** [comment]
This is something I would vehemently oppose. escope operates on estree ASTs. FunctionExpression nodes must have a body, so escope may safely assume that it is there.

**Comment by corbinu** [comment]
@michaelficarra I am sorry just am a little confused this is a kind of TypeAnnotation no? Which is defined for estree

https://github.com/estree/estree/blob/master/extensions/type-annotations.md

So is the issue that we should instead make a change to attach the additional method type declarations to the main Function expression? that way it for sure has the body

**Comment by michaelficarra** [comment]
All FunctionExpression nodes must have a body, and the type annotations extension to estree does not change that fact.

I can't understand the rest of your comment.

**Comment by corbinu** [comment]
@michaelficarra Yes I specifically proposed a solution that would give them all a body. I am saying that these statements are not really functions anyway they are TypeAnnotations. So the correct solution would be to attach them to the FunctionExpression they are annotating that does have a body. Rather than at the moment where they are treated as a separate FunctionExpression without a body.

**Comment by michaelficarra** [comment]
Please paste a minimal repro case with observed and expected behaviour so we can stop miscommunicating.

**Comment by corbinu** [comment]
@michaelficarra @JamesHenry linked the issue with the repo case when he created this issue. Here is is again:

estools fails errors on the following:
```
export class Test {

    constructor() {
    }

    public test(param1: Number): Test;
    public test(param1: Test): Test;
    public test(param1: any): Test {
        return new Test();
    }

}
```

At the moment `public test(param1: Number): Test;` is being treated as a FunctionExpression without a body. So our simple solution was to allow function expressions to not have a body. You have argued that since FunctionExpressions must have a body this is incorrect. I am not disagreeing with that and instead arguing `public test(param1: Number): Test;` is technically not a FunctionExpression it is a form of TypeAnnotation.

```
public test(param1: any): Test {
   return new Test();
}
```
However is a valid FunctionExpression. So I am suggesting that rather than treat `public test(param1: Number): Test;` as a separate FunctionExpression it instead should be attached to
```
public test(param1: any): Test {
   return new Test();
}
```
as additional type information. 

@JamesHenry probably knows better than I how this would be accomplished in escope and how much would be in in the typescript-eslint-parser.

I get that this is not a technical solution but your argument against this was existential not technical. So it seems the first thing we need to figure out is how existentially these types fit into ESTree (which I was simply pointing out their is precedent for). Then we can build a technical solution from there. 

I would like to note I have also proposed to the eslint team that perhaps it is better to simply allow eslint parsers inject their own analyzer rather than always using escope. That way we could simply fork a "tscope" as it were and then the eslint-typescript-paser could use that and eslint standard would simply continue using escope.

**Comment by michaelficarra** [comment]
It seems your parser is outputting an AST that is like estree but with an extension that is not permitted. If you would like your parser to output something that can work with escope, you will have to take it up with them. escope will continue to support only estree and its official extensions.
