### ISSUE TITLE
Top level variables don't have references assigned

### ISSUE THREAD

**Issue by jbrumwell** [estools/escope#56]
Give the following code and using http://mazurov.github.io/escope-demo/;

```js
const a = 'b';
a = 'c';
testing(a);
```

You can see the variable `a` has an empty references property here, The references are available under `scope.references` just not attached to the variable.

**Comment by mysticatea** [comment]
I got same bug.

```js
var a = 0;
function foo() {
  a = 1;
}
```

In this case, `references` of `a` becomes an empty array.
I expect it to be 2 references; `a = 0` and `a = 1`.

Each scope have a reference that its `Reference.resolved` property is `null`.

**Comment by michaelficarra** [comment]
For top-level `var`s, this behaviour makes sense: you can't tell if that will be a reference or not because the scope is dynamic:

```js
var a = 0;
delete global.a;
a = 1;
```

Technically, we can be certain that the initialisation is a reference, so we could have either one or zero references. But I like the consistency of never tracking references for variables in dynamic scopes.

For `let`/`const` variables, though, the references should be tracked. That is a bug.

**Comment by mysticatea** [comment]
Thanks for explain!
I got it.

**Comment by mysticatea** [comment]
I'm trying to fix this issue: https://github.com/mysticatea/escope/commit/c644d820012a9f19ef1d5f03bf584a0548eaffd5

Now, it became passing very simple test cases.
But I'm worried about whether the direction of modifications is correct.

I modified `Scope.prototype.__close` method.
If the scope is the top-level, checks whether each reference is `let/const/class`'s.

I have not found the meaning that `Variable`'s `defs` is an array yet.
I'm going to add more test cases.

I'm sorry, my poor English...
Thanks.

**Comment by Constellation** [comment]
Great! Let's send pull request!
